name: "ci"

on:
  push:
    branches: ["master"]
    tags: ["v*"]
  pull_request:
    branches: ["master"]

env:
  COVERALLS_VERSION: "2.1.1"
  DEV_PYTHON_VERSION: "3.8"
  POETRY_VERSION: "1.0.10"
  TWINE_VERSION: "3.1.1"

jobs:
  dev:
    name: "Verify package is installed well"

    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]

    runs-on: "${{ matrix.os }}"

    steps:
      - uses: "actions/checkout@v2.3.2"

      - name: "Install Python"
        uses: "actions/setup-python@v2.1.2"
        with:
          python-version: "${{ env.DEV_PYTHON_VERSION }}"

      - name: "Install poetry"
        uses: "dschep/install-poetry-action@v1.3"
        with:
          version: "${{ env.POETRY_VERSION }}"

      - name: "Install package"
        run: "poetry install --no-dev"

      - name: "Import package"
        run: "poetry run python -c 'import pre_commit_run_hook_entry'"

  test:
    name: "Python ${{ matrix.python-version }}"

    strategy:
      matrix:
        python-version: ["3.7", "3.8"]

    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v2.3.2"

      - name: "Install Python"
        uses: "actions/setup-python@v2.1.2"
        with:
          python-version: "${{ matrix.python-version }}"

      - name: "Install poetry"
        uses: "dschep/install-poetry-action@v1.3"
        with:
          version: "${{ env.POETRY_VERSION }}"

      - name: "Install package"
        run: |
          poetry install

      - name: "Run pre-commit"
        uses: "pre-commit/action@v2.0.0"

      - name: "Run tests"
        run: |
          set -e

          if [ "${{ matrix.python-version }}" != "${{ env.DEV_PYTHON_VERSION }}" ]; then
            export PYTEST_ADDOPTS="--no-cov"
          fi

          poetry run python -m pytest

      - name: "Send report to coveralls"
        if: "matrix.python-version == env.DEV_PYTHON_VERSION"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          python -m pip install coveralls==${{ env.COVERALLS_VERSION }}
          python -m coveralls

  package:
    needs: "test"
    name: "Build & deploy package"

    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v2.3.2"

      - name: "Install Python"
        uses: "actions/setup-python@v2.1.2"
        with:
          python-version: "${{ env.DEV_PYTHON_VERSION }}"

      - name: "Install poetry"
        uses: "dschep/install-poetry-action@v1.3"
        with:
          version: "${{ env.POETRY_VERSION }}"

      - name: "Build package"
        run: "poetry build"

      - name: "Check package"
        run: |
          python -m pip install twine==${{ env.TWINE_VERSION }}
          python -m twine check dist/*

      - name: "Publish package"
        if: "github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')"
        uses: "pypa/gh-action-pypi-publish@v1.3.1"
        with:
          user: "${{ secrets.PYPI_USERNAME }}"
          password: "${{ secrets.PYPI_PASSWORD }}"

  release:
    if: "startsWith(github.ref, 'refs/tags')"
    needs: "package"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v2.3.2"

      - name: "Fetch git data"
        run: |
          set -e
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          git fetch --prune --unshallow

      - id: "release-info"
        name: "Prepare release info"
        run: |
          set -e

          tag_name=${GITHUB_REF:10}
          echo "::set-output name=tag_name::${tag_name}"

          subject=$(git tag -l --format="%(subject)" ${tag_name})
          echo "::set-output name=subject::${subject}"

          body=$(git tag -l --format="%(body)" ${tag_name})
          # Preserve multiline strings as per
          # https://github.community/t/set-output-truncates-multiline-strings/16852/5
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          echo "::set-output name=body::${body}"

          prerelease=false
          if [ -z "${tag_name##*a*}" -o -z "${tag_name##*b*}" -o -z "${tag_name##*rc*}" ]; then
            prerelease=true
          fi
          echo "::set-output name=prerelease::${prerelease}"

      - name: "Create new release"
        uses: "actions/create-release@v1.1.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          tag_name: "${{ steps.release-info.outputs.tag_name }}"
          release_name: "${{ steps.release-info.outputs.subject }}"
          body: "${{ steps.release-info.outputs.body }}"
          prerelease: "${{ steps.release-info.outputs.prerelease }}"
