name: "ci"

on:
  push:
    branches: ["master"]
    tags: ["v*"]
  pull_request:
    branches: ["master"]

env:
  DEV_PYTHON_VERSION: "3.8"
  POETRY_VERSION: "1.0.5"
  TWINE_VERSION: "3.1.1"

jobs:
  dev:
    name: "Verify package is installed well"

    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]

    runs-on: "${{ matrix.os }}"

    steps:
      - uses: "actions/checkout@v2.0.0"

      - name: "Install Python"
        uses: "actions/setup-python@v1.2.0"
        with:
          python-version: "${{ env.DEV_PYTHON_VERSION }}"

      - name: "Install poetry"
        uses: "dschep/install-poetry-action@v1.3"
        with:
          version: "${{ env.POETRY_VERSION }}"

      - name: "Install package"
        run: "poetry install --no-dev"

      - name: "Import package"
        run: "poetry run python -c 'import pre_commit_run_hook_entry'"

  test:
    name: "Python ${{ matrix.python-version }}"

    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8"]

    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v2.0.0"

      - name: "Install Python"
        uses: "actions/setup-python@v1.2.0"
        with:
          python-version: "${{ matrix.python-version }}"

      - name: "Install poetry"
        uses: "dschep/install-poetry-action@v1.3"
        with:
          version: "${{ env.POETRY_VERSION }}"
          create_virtualenvs: true

      - name: "Install package"
        run: |
          poetry config virtualenvs.in-project true
          poetry install --no-dev

      - name: "Cache pre-commit"
        if: "matrix.python-version == env.DEV_PYTHON_VERSION"
        uses: "actions/cache@v2.0.0"
        with:
          path: "~/.cache/pre-commit"
          key: "pre-commit-${{ matrix.python-version }}-${{ hashFiles('.pre-commit-config.yaml') }}"

      - name: "Run pre-commit"
        if: "matrix.python-version == env.DEV_PYTHON_VERSION"
        uses: "pre-commit/action@v1.0.1"

  package:
    needs: "test"
    name: "Build & deploy package"

    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v2.0.0"

      - name: "Install Python"
        uses: "actions/setup-python@v1.2.0"
        with:
          python-version: "${{ env.DEV_PYTHON_VERSION }}"

      - name: "Install poetry"
        uses: "dschep/install-poetry-action@v1.3"
        with:
          version: "${{ env.POETRY_VERSION }}"
          create_virtualenvs: true

      - name: "Build package"
        run: "poetry build"

      - name: "Check package"
        run: |
          python -m pip install twine==${{ env.TWINE_VERSION }}
          python -m twine check dist/*

      - name: "Publish package"
        if: "github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')"
        uses: "pypa/gh-action-pypi-publish@v1.1.0"
        with:
          user: "${{ secrets.PYPI_USERNAME }}"
          password: "${{ secrets.PYPI_PASSWORD }}"
