defaults:
  run:
    shell: "bash"

name: "CI"

on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["main"]

env:
  PYTHONUNBUFFERED: "1"

jobs:
  dev:
    name: "Verify package is installed well"

    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]

    runs-on: "${{ matrix.os }}"

    steps:
      - uses: "actions/checkout@v3.0.2"

      - uses: "./.github/actions/install_python_and_poetry"
        with:
          cache-key-suffix: "-main"
          python-version-file: ".python-version"

      - name: "Install package"
        run: "poetry install --only main"

      - name: "Import package"
        run: "poetry run python3 -c 'from pre_commit_run_hook_entry.cli import main'"

  test:
    name: "Test package"

    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v3.0.2"

      - id: "python_and_poetry"
        uses: "./.github/actions/install_python_and_poetry"
        with:
          cache-key-suffix: "-main-dev-test"
          python-version-file: ".python-version"

      - uses: "./.github/actions/run_pre_commit"
        with:
          python-version: "${{ steps.python_and_poetry.outputs.python-version }}"

      - uses: "./.github/actions/run_tox"
        with:
          python-path: "${{ steps.python_and_poetry.outputs.python-path }}"
          python-version: "${{ steps.python_and_poetry.outputs.python-version }}"
          use-coveralls: "true"
          coveralls-token: "${{ secrets.GITHUB_TOKEN }}"

  package:
    needs: ["test"]

    uses: "./.github/workflows/ci_package.yml"
    secrets:
      pypi-user: "${{ secrets.PYPI_USERNAME }}"
      pypi-password: "${{ secrets.PYPI_PASSWORD }}"

  release:
    needs: ["package"]
    if: "${{ startsWith(github.ref, 'refs/tags/') }}"

    uses: "./.github/workflows/ci_release.yml"
    secrets:
      release-token: "${{ secrets.GITHUB_TOKEN }}"
